name: Daily Python Script

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest  # You can specify other OS types if needed

    env:
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Specify the Python version

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Extract Data to Mongodb script
        run: |
          python extractDataFromCoingecko.py
      
      - name: Send email
        run: |
          python send_email.py